### ISSUE TITLE
php 7 dropped with spatie/macroable v2

### ISSUE THREAD

**Issue by bnomei** [genxbe/kirby3-ray#1]
also see
https://github.com/spatie/ray/pull/426

march 26: v2
https://github.com/spatie/macroable/releases

you might need to
`composer require spatie/macroable:1.0.1` fot php 7 support.

**Comment by bnomei** [comment]
sorry should have been v `1.0.1`

**Comment by samzzi** [comment]
Thanks for your suggestion, fixed in 1.0.1. I hope I did everything right, these are my first adventures in managing a public package 😊
