### ISSUE TITLE
Errors trigger error without error

### ISSUE THREAD

**Issue by medienbaecker** [genxbe/kirby3-ray#4]
Sorry for the cheeky title. PR https://github.com/genxbe/kirby3-ray/pull/3 introduced an error when handling errors.

To reproduce:

1. Put an erroneous code somewhere. Example: `<?= 'test'->slug() ?>` in the `default.php` template.
2. You'd expect an error like "Call to a member function slug() on string" but instead you receive:
```
"Uncaught TypeError: Spatie\Ray\Ray::exception(): Argument #1 ($exception) must be of type Exception, Error given, called in /site/plugins/kirby3-ray/index.php on line 56
```

It seems like you get an `Error` instead of an `Exception` from the hook and Ray doesn't like that. Disabling the plugin or downgrading to 1.0.1 works.

Maybe add a `get_class($exception)` check?

**Comment by samzzi** [comment]
Hi @medienbaecker, thx for your feedback! (And apologies for answering so late, need to check my github notifications)

Although... I'm having a hard time to reproduce the error, it seems to work like expected (screenshot: https://x.gnx.li/sbAIo8). Did you do anything else except the `<?= 'test'->slug() ?>`? 🤔

Either way, i upgraded the Ray version already on the develop branch, maybe that helps? 😬 

Cheers!

Sam

**Comment by medienbaecker** [comment]
Hi @samzzi, thanks for checking! It does indeed not happen on the develop branch. It seems like Ray can handle the `Error` now 👍

Cheers!

**Comment by samzzi** [comment]
> 

Cool, I'll merge it to main later on. Thanks for your feedback!
