### ISSUE TITLE
php 8.2 -> mb_convert_encoding(): Handling HTML entities via mbstring is deprecated

### ISSUE THREAD

**Issue by bvdputte** [genxbe/kirby3-ray#6]
I'm getting errors when using this plugin icw PHP 8.2:

`Fatal error: Uncaught Whoops\Exception\ErrorException: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in .../starterkit.test/site/plugins/kirby3-ray/vendor/symfony/var-dumper/Dumper/HtmlDumper.php on line 963`.

Probably related to https://github.com/symfony/symfony/issues/44281 ?

**Comment by samzzi** [comment]
This was because macroable was on a fixed version for php 7 compatibility. I've tagged a new version of this plugin (2.0) that drops php 7 and works with 8.2. Thx for reporting this!

**Comment by bvdputte** [comment]
Thx! Can you also include the changed dependencies from composer to the repo too?
(For the few of us that don't use composer to manage plugins)

Thx! 🙏
