### ISSUE TITLE
Support for panel update checks, broken in 2.0

### ISSUE THREAD

**Issue by tobimori** [genxbe/kirby3-ray#7]
<img width="338" alt="CleanShot 2023-03-21 at 12 32 29@2x" src="https://user-images.githubusercontent.com/29142128/226594126-d93244cb-d7f8-4083-a3be-75159501711e.png">

**Comment by sam-kdg** [comment]
Fixed in 2.0.1. Apparently I was a bit quick with the plugin name change. Apologies!

**Comment by samzzi** [comment]
Fixed in 2.0.1. Apparently I was a bit quick with the plugin name change. Apologies!
